# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8e9b030c12d63b46eb39b0825da43cbf5cfa6b723b2df151f3be15549804e2976fbf0d9737f62c66a93d18f7581df9cea8821148770decd95b928ed089c02f8c

test:
  secret_key_base: 538d252e6f801bd3157d52bfb94228980fc17da0b01a5215d2d39732bb3fa97a374d8e5e2a31c75b47eb0e196b05d04a82d2a574a75d4e076f168e0bfd9c3304

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
